#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D
picom --experimental-backends &
yabar &
deadd-notification-center &
# $HOME/polybar-collection/launch.sh
# nitrogen --restore &
xrdb ~/.Xresources
~/.fehbg

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^6' state=tiled follow=on
bspc rule -a Kodi desktop='^7' follow=on
bspc rule -a firefox desktop='^3' state=fullscreen follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a jetbrains-idea-ce desktop='^4' state=floating follow=on
bspc rule -a jetbrains-studio desktop='^5' state=floating follow=on
bspc rule -a jetbrains-pycharm-ce desktop='^4' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a XTerm state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
